export const enum_tipo_documento = [
   { label: "Cedula de Ciudadania", value: "CC" },
   { label: "Tarjeta de Identidad", value: "TI" },
   { label: "Cedula de Extranjeria", value: "CE" },
   { label: "Pasaporte", value: "PPT" },
];
export const enum_tipo_rh = [
   { label: "O+", value: "O+" },
   { label: "O-", value: "O-" },
   { label: "A+", value: "A+" },
   { label: "A-", value: "A-" },
   { label: "B+", value: "B+" },
   { label: "B-", value: "B-" },
   { label: "AB+", value: "AB+" },
   { label: "AB-", value: "AB-" },
];
export const enum_estado_civil = [
   { label: "Soltero", value: "SOLTERO" },
   { label: "Casado", value: "CASADO" },
   { label: "Divorciado", value: "DIVORCIADO" },
   { label: "Viudo", value: "VIUDO" },
   { label: "Separado", value: "SEPARADO" },
   { label: "Union libre", value: "UNION LIBRE" },
];
export const enum_sexo = [
   { label: "Masculino", value: "M" },
   { label: "Femenino", value: "F" },
];
export const enum_tipo_sangre = [
   { label: "O+", value: "O+" },
   { label: "O-", value: "O-" },
   { label: "A+", value: "A+" },
   { label: "A-", value: "A-" },
   { label: "B+", value: "B+" },
   { label: "B-", value: "B-" },
   { label: "AB+", value: "AB+" },
   { label: "AB-", value: "AB-" },
];
export const paises = [
   { label: "Argentina", value: "argentina" },
   { label: "Bolivia", value: "bolivia" },
   { label: "Brasil", value: "brasil" },
   { label: "Chile", value: "chile" },
   { label: "Colombia", value: "colombia" },
   { label: "Costa Rica", value: "costa_rica" },
   { label: "Cuba", value: "cuba" },
   { label: "Ecuador", value: "ecuador" },
   { label: "El Salvador", value: "el_salvador" },
   { label: "Guatemala", value: "guatemala" },
   { label: "Honduras", value: "honduras" },
   { label: "México", value: "mexico" },
   { label: "Nicaragua", value: "nicaragua" },
   { label: "Panamá", value: "panama" },
   { label: "Paraguay", value: "paraguay" },
   { label: "Perú", value: "peru" },
   { label: "Puerto Rico", value: "puerto_rico" },
   { label: "República Dominicana", value: "republica_dominicana" },
   { label: "Uruguay", value: "uruguay" },
   { label: "Venezuela", value: "venezuela" },
];
export const departamentos = [
   { label: "Antioquia", value: "antioquia" },
   { label: "Bogotá", value: "bogota" },
   { label: "Cundinamarca", value: "cundinamarca" },
   { label: "Valle del Cauca", value: "valle del cauca" },
   { label: "Atlántico", value: "atlantico" },
];
export const ciudades = [
   { label: "Medellín", value: "medellin", departamento: "antioquia" },
   { label: "Bello", value: "bello", departamento: "antioquia" },
   { label: "Itagüí", value: "itagui", departamento: "antioquia" },
   { label: "Envigado", value: "envigado", departamento: "antioquia" },
   { label: "Rionegro", value: "rionegro", departamento: "antioquia" },
   { label: "Bogotá", value: "bogota", departamento: "bogota" },
   { label: "Soacha", value: "soacha", departamento: "cundinamarca" },
   { label: "Zipaquirá", value: "zipaquira", departamento: "cundinamarca" },
   { label: "Chía", value: "chia", departamento: "cundinamarca" },
   { label: "Facatativá", value: "facatativa", departamento: "cundinamarca" },
   { label: "Cali", value: "cali", departamento: "valle del cauca" },
   { label: "Palmira", value: "palmira", departamento: "valle del cauca" },
   { label: "Buenaventura", value: "buenaventura", departamento: "valle del cauca" },
   { label: "Tuluá", value: "tulua", departamento: "valle del cauca" },
   { label: "Barranquilla", value: "barranquilla", departamento: "atlantico" },
   { label: "Soledad", value: "soledad", departamento: "atlantico" },
   { label: "Malambo", value: "malambo", departamento: "atlantico" },
   { label: "Sabanalarga", value: "sabanalarga", departamento: "atlantico" },
];
export const enum_vacunas_covid = [
   { value: "pfizer", label: "Pfizer" },
   { value: "moderna", label: "Moderna" },
   { value: "astrazeneca", label: "AstraZeneca" },
   { value: "janssen", label: "Johnson & Johnson" },
   { value: "sinovac", label: "Sinovac" },
   { value: "sinopharm", label: "Sinopharm" },
   { value: "covaxin", label: "Covaxin" },
   { value: "sputnik", label: "Sputnik V" },
   { value: "novavax", label: "Novavax" },
   { value: "otra", label: "Otra / No especificada" },
]